-- MySQL Script generated by MySQL Workbench
-- Sat Mar 27 22:05:52 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mynote
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mynote
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mynote` DEFAULT CHARACTER SET utf8 ;
USE `mynote` ;

-- -----------------------------------------------------
-- Table `mynote`.`mynote_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mynote`.`mynote_data` (
  `number` INT NOT NULL AUTO_INCREMENT,
  `start_date` TIMESTAMP NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `note_header` VARCHAR(255) NOT NULL,
  `note_detail` LONGTEXT NOT NULL,
  PRIMARY KEY (`number`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
